---
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  
  roles:
    - common
    - kosssi.gitconfig

    # Web Server
    - jdauphant.nginx

    # Languages and package managers
    - geerlingguy.nodejs
    - geerlingguy.php
    - geerlingguy.composer
    - rvm_io.ruby
    - joshualund.golang

    # Desktop software
    - gantsign.atom
    - gantsign.gitkraken
    - cmprescott.chrome

    # Containers
    - angstwad.docker_ubuntu
    - gantsign.kubernetes
    #- geerlingguy.docker
