---
- name: Install core packages
  apt: pkg={{item}} state=present
  with_items:
    - build-essential
    - gcc
    - g++
    - git
    - python-gpgme
    - curl
    - gnupg
    - python-pycurl
    - gnupg-curl
    - less
    - htop
    - iotop
    - tree
    - python-apt
    - wine
    - virtualbox
    - nmap
    - traceroute
    - python-dev
    - libevent-dev
    - python-pip
    - python-setuptools
    - gconf-editor
    - libcurl3 # gitkraken dependency
     # flux
    - redshift
    - gtk-redshift


- name: Configure redshift
  template:
    dest:  "/home/{{ username }}/.config/redshift.conf"
    src: redshift.conf.j2
